### ISSUE TITLE
FC004 false positive (Windows start command)

### ISSUE THREAD

**Issue by vtintillier** [Foodcritic/foodcritic#306]
This is detected as FC004

``` ruby
execute 'Run setup' do
  command "start /wait my_setup.exe --silent"
end
```

The `start` command is not related to services on Windows.

**Comment by tas50** [comment]
@vtintillier This is resolved by https://github.com/Foodcritic/foodcritic/pull/702. I added your example to the specs so we make sure we don't introduce a regression later on. Thanks for the report. Sorry this took so incredibly long.
