### ISSUE TITLE
FC039 triggers with default['role_default']['add_webproxy'] = false

### ISSUE THREAD

**Issue by mrmarbury** [Foodcritic/foodcritic#428]
Hi,

I have the following problem. In my cookbook `role_default`, I set the above default attribute. In the default recipe I use it as `node['role_default']['add_webproxy'] == true` in an if statement to include a recipe as needed. For both FC complains that:

FC039: Node method cannot be accessed with key: cookbooks/role_default/attributes/default.rb:1
FC039: Node method cannot be accessed with key: cookbooks/role_default/recipes/default.rb:10

Why is FC complaining about this? I cannot see that `role_default` is a node method

Cheers and thanks for clearing that up,
Stefan

**Comment by lamont-granquist** [comment]
`role_default` is one of the precedence levels of chef-client, and that is a method on the node object via the delegation to chef/node/attribute:

https://github.com/chef/chef/blob/2b0fb5b6249c2b456aa38ef8daf90f5739d6770a/lib/chef/node/attribute.rb#L167-L168

this is correctly throwing an error that the user probably meant `node.role_default['add_webproxy'] = true`

if that isn't the intent and you really want to name a top level attribute `role_default` that's somewhat confusing, but your choice, and you should override FC039 for that line, but this is actually an example of FC039 firing correctly.

**Comment by mrmarbury** [comment]
Okay, I can see now why that fails. Thing is that the customer named a Role cookbook "role_default" since it defines a default for all servers. And therefore the namespace of the attributes would also be 'role_default'.
