### ISSUE TITLE
Chef 13: Alert if someone uses Chef::Platform methods

### ISSUE THREAD

**Issue by tas50** [Foodcritic/foodcritic#587]
Alert if someone uses Chef::Platform.provider_for_resource or Chef::Platform.find_provider should alert as these methods have been removed from Chef 13

https://docs.chef.io/deprecations_chef_platform_methods.html

**Comment by vinyar** [comment]
wondering if this is necessary? chef client 12.39 will throw a warning and chef client 13 will fail in compilation phase ;)

**Comment by tas50** [comment]
Without a foodcritic test we have no way to analyze existing cookbooks on the Supermarket and no way for users on older chef clients to gauge the scope of work involved in an upgrade. The goal here is that every deprecation comes with a rule if it's possible to do so with static analysis.

**Comment by tas50** [comment]
FC087 handles these all now!
