### ISSUE TITLE
FC069, FC078 do not apply for private cookbooks

### ISSUE THREAD

**Issue by iancward** [Foodcritic/foodcritic#609]
The undocumented FC078 (osi-approved license) and the FC069 (standardized license) don't honor the "privacy" boolean in the cookbook metadata. 
That is to say, if you mark a cookbook as "private", there should be no requirement for an open source licensed.

Also, if you set the license string to "UNLICENSED", meaning that it is not licensed to be used externally, FC071 (missing LICENSE file) also triggers.

**Comment by coderanger** [comment]
Use the license string `"All rights reserved"`

**Comment by iancward** [comment]
I have "All rights reserved" in the license, but foodcritic still flagged the metadata with FC078 and FC069. If I changed it from "All rights reserved" to "UNLICENSED", I also got FC071.

**Comment by coderanger** [comment]
It can't just include that, it has to be just "All Rights Reserved". And 078 should only be active on Supermarket I think.

**Comment by iancward** [comment]
Sorry, I meant to say the value of `license` was `'All rights reserved'`. So with that, I flags metadata.rb with FC078 and FC069. I've also opened #610 as FC078 and FC069 don't use the same tags.

**Comment by coderanger** [comment]
Looking at the code it might actually be case sensitive, which should be fixed.

**Comment by iancward** [comment]
ok, "All Rights Reserved" made FC069 happy. I didn't scroll all the way down to find https://github.com/Foodcritic/foodcritic/blob/master/lib/foodcritic/rules/fc069.rb#L359. FC078 still complains, though.

While `privacy` is in the documentation for [`metadata.rb`](https://docs.chef.io/config_rb_metadata.html), there isn't any usage documentation for it. It would be nice to use that as a trigger to disable any and all license checks, so that we don't have to worry about case sensitive things. That would also make sense, since "All Rights Reserved" isn't technically a valid SPDX license expression.

**Comment by tas50** [comment]
So FC078 is designed to fire when you use an all rights reserved license. It can be disabled if you're not sharing cookbooks, but that will be a change you need to make in your cookbooks individually or within your CI pipeline. At it's core Foodcritic is designed for cookbooks that are shared.

As far as privacy goes we'll have to look at that one. We've never actually utilized that anywhere within Supermarket or Chef.

FC069 will respect "All rights reserved" which is the standard non open source licensed string we use as generated by Chef generate cookbook foo.

**Comment by tas50** [comment]
Check out Foodcritic 11, which includes the additional tags and also accepts more forms of all rights reserved. It should resolve your issues.

**Comment by nishanthkumar23** [comment]
FC078 is failing for me.it shows ' Ensure cookbook shared under an OSI-approved open source license'.
i have changed licence to 'All Rights Reserved' and 'UNLICENSED'. But not able to overcome problem here. How do i utilize 'SPDX.org' when i writing cookbook for .net applications in windows environment?
