### ISSUE TITLE
Add tags to FC078

### ISSUE THREAD

**Issue by iancward** [Foodcritic/foodcritic#610]
To work around #609 I need to add add some rule exclusions to my `.foodcritic` file. I'd like to use a tag to capture both of them; however, the rules don't use the same tags.
Since FC069 has `metadata supermarket license`, it would be nice if FC078 added the same tags. That way, I could just add `~license` to my `.foodcritic` file until #609 is addressed.

**Comment by tas50** [comment]
it's currently tagged with opensource which will allow you to disable it. I can add license as well

**Comment by tas50** [comment]
Fixed by #611
