### ISSUE TITLE
Update FC085 to detect @new_resource usage

### ISSUE THREAD

**Issue by tas50** [Foodcritic/foodcritic#619]
Right now we only fire on new_resource. We should fire on both new_resource and @new_resource as both are used extensively in community cookbooks

**Comment by flaccid** [comment]
I'm already feeling this?
`FC085: Resource using new_resource.updated_by_last_action to converge resource: ./providers/environment.rb:29`

**Comment by tas50** [comment]
There's 137 uses of @new_resource.updated_by_last_action on the supermarket so it's definitely worth finding
