### ISSUE TITLE
RuleDsl - recipe block is not only applied to recipes

### ISSUE THREAD

**Issue by bigCrash** [Foodcritic/foodcritic#623]
I wrote the following rule:
```ruby
rule 'TES01', '140chars' do
  tags %w{style long_statement}
  recipe do |ast, file|
    lines = File.readlines(file)
    lines.collect.with_index do |line, index|
      if line.length > 140
        {
          :filename => file,
          :matched => file,
          :line => index + 1,
          :column => 0
        }
      end
    end.compact
  end
end
```

This rule is only  for recipes, but it is also applied to template files, attribute files and e.g. the metadata.rb. Is this by design?

**Comment by tas50** [comment]
recipe was a poorly named segment name. It, by design, pulls in a pile of different files. That ship sailed unfortunately and people rely on the extra files that come in so we can't really change it now.
