### ISSUE TITLE
Alert if a guard has a standalone string inside brackets.

### ISSUE THREAD

**Issue by jjustice6** [Foodcritic/foodcritic#627]
We've had this mistake come up, and foodcritic didn't catch it:

A guard will exist, something like this:
`not_if 'some_command'`
Later on, someone realizes the guard should be more complex, and adds an additional _ruby_ rule:

`not_if { 'some_command' || some_ruby_function() }`

This doesn't work as expected, since 'some_command' is just a string in this context.

I believe this should trigger a warning from Foodcritic.

**Comment by tas50** [comment]
This should trigger Foodcritic, but with static analysis there's really no way for us to distinguish between command and a function. I'm going to close this out as a won't fix simply because I can't think of a way to fix it.
