### ISSUE TITLE
Indicate files and templates are managed by Chef

### ISSUE THREAD

**Issue by iancward** [Foodcritic/foodcritic#635]
It would be nice if Foodcritic enforced phrases similar to "This file is managed by chef; local modifications will be overwritten" in templates and files that Chef renders. That way, an end-user can be certain that the file is, in fact, managed by Chef.

**Comment by coderanger** [comment]
Not all formats support comments and those that do have no unified formatting. Probably not worth chasing this.

**Comment by iancward** [comment]
Ah, I see what you mean. Maybe just templates then, since those are rendered as text?

**Comment by coderanger** [comment]
But we have no idea what kind of file it is.

**Comment by tas50** [comment]
I think we're going to have to close this one out. Like @coderanger said not everything can have a comment. In fact a lot of comments can't so this would be incredibly problematic.
