### ISSUE TITLE
food critic should check for platform version format

### ISSUE THREAD

**Issue by bharathcp** [Foodcritic/foodcritic#636]
The `supports` platform version line of `metadata.rb` should be compliant to `x.y.z` or `x.y` format. Without this supermarket upload will fail with below error:
```
{"error_code"=>"INVALID_DATA", "error_messages"=>["Version constraint is not a valid Chef version constraint. Chef::Exceptions::InvalidCookbookVersion: '7' does not match 'x.y.z' or 'x.y'"]}
```
wrong format:
`supports 'centos', '>= 7'`
correct format:
`supports 'centos', '>= 7.3'`
There should be a rule that checks this.

**Comment by tas50** [comment]
@bharathcp What command are you running to do the upload?

**Comment by tas50** [comment]
Closing this out due to lack of response. The 2nd field in the version uploads really shouldn't be an issue and it's something that chef doesn't actually consume right now. If we're failing to upload that to Supermarket via stove or knife that's a bug there.
