### ISSUE TITLE
False FC009 in package/yum/package for allow_downgrade attribute

### ISSUE THREAD

**Issue by voroniys** [Foodcritic/foodcritic#642]
Throws FC009 if in yum_package resource attribute `allow_downgrade` is used

**Comment by tas50** [comment]
What version of foodcritic are you running into this with?

**Comment by voroniys** [comment]
The one that comes with chefdk 1.3.43 - 10.2.2

**Comment by tas50** [comment]
Can you paste the exact code that's failing?

**Comment by tas50** [comment]
Closing this out since we never got a response with failing code. If you want to open this back up with some example code I'll dig in and see what I can do
