### ISSUE TITLE
FC086 false positive for Chef::EncryptedDataBagItem.load_secret.

### ISSUE THREAD

**Issue by itmustbejj** [Foodcritic/foodcritic#647]
The Xpath query is looking for EncryptedDataBagItem or DataBagItem to suggest using data_bag_item instead.
https://github.com/Foodcritic/foodcritic/blob/master/lib/foodcritic/rules/fc086.rb#L4

Unfortunately, it also fails when you are calling `EncryptedDataBagItem.load_secret` to load the secret for data_bag_item.

See: https://github.com/chef/chef-web-docs/pull/729

**Comment by tas50** [comment]
This is fixed in the most recent version of Foodcritic
