### ISSUE TITLE
metadata.rb contains correct entry - license 'All Rights Reserved' However the error still pesists FC078: Ensure cookbook shared under an OSI-approved open source license: ./metadata.rb:1 How to solve???

### ISSUE THREAD

**Issue by cloudsavara** [Foodcritic/foodcritic#655]

**Comment by coderanger** [comment]
This has been disabled by default in newer Foodcritic but if you've re-enabled it you need to make sure that the `license` string in your metadata file is one of the SPDX license strings recognized as being an open-source license.

**Comment by cloudsavara** [comment]
Could you plz let me know, how to correct it. Please find the log and command details.

$ foodcritic . -t ~FC064 -t ~FC065
Checking 4 files
x...
FC078: Ensure cookbook shared under an OSI-approved open source license: ./metadata.rb:1
$ cat metadata.rb 
name 'lcd_web'
maintainer 'Student Name'
maintainer_email 'vara@example.com'
#license 'Proprietary - All Rights Reserved'
license 'All Rights Reserved'
#license 'UNLICENSED'
#license 'MIT'
description 'Installs/Configures lcd_web'
long_description 'Installs/Configures lcd_web'
version '0.1.0'
#chef_version '>= 12.1' if respond_to?(:chef_version)
chef_version '~> 12'
supports 'redhat'
# The `issues_url` points to the location where issues for this cookbook are
# tracked.  A `View Issues` link will be displayed on this cookbook's page when
# uploaded to a Supermarket.
#
# issues_url 'https://github.com/<insert_org_here>/lcd_web/issues'

# The `source_url` points to the development repository for this cookbook.  A
# `View Source` link will be displayed on this cookbook's page when uploaded to
# a Supermarket.
#
# source_url 'https://github.com/<insert_org_here>/lcd_web'

**Comment by cloudsavara** [comment]
[555.txt](https://github.com/Foodcritic/foodcritic/files/1151496/555.txt)

**Comment by coderanger** [comment]
I've already told you how to fix it, you have `All Rights Reserved` as your license string which is not an open source license. Unfortunately the details of picking a license are up to you and whatever lawyers you work with. In the future, please don't use Github Issues for non-bug-report requests, you can use the Chef community Slack channel or mailing list. I'm going to lock this ticket now.
