### ISSUE TITLE
Run rubocop for this project in Travis CI

### ISSUE THREAD

**Issue by martinmosegaard** [Foodcritic/foodcritic#667]
We have a `.rubocop.yml` configuration file, but I get many violations when I run rubocop (0.50.0). We could start by auto-generating a config file for the violations and then gradually remove them.

`rubocop . --auto-gen-config`

and then add to `.rubocop.yml`:
`inherit_from: .rubocop_todo.yml`

and then execute rubocop in `.travis.yml`

**Comment by coderanger** [comment]
You need to run `chefstyle` instead.

**Comment by martinmosegaard** [comment]
Thanks for clarifying!
