### ISSUE TITLE
FC006: Allow "0o" prefixed octal

### ISSUE THREAD

**Issue by stefanor** [Foodcritic/foodcritic#673]
Rubocop converts `0`-prefixed octal to `0o`-prefixed versions (see bbatsov/rubocop#3123). This is in line with other programming languages that are trying to get away from C's confusing 0-prefixed octal.

This should be allowed by foodcritic, I think.

`0o755` is clearly an octal number. And if you haven't seen this syntax before, I don't think you're going to change it to `4o755` when you add a setuid bit. Which is the mistake that FC006 is trying to prevent.

**Comment by coderanger** [comment]
We prefer you use strings for file modes. While it is very occasionally useful to treat file modes as numbers, it's much less error prone to treat then as string data.

**Comment by coderanger** [comment]
Also we recommend you use cookstyle with Chef cookbooks, which has some changes to the default Rubocop config for reasons like this, though it doesn't directly matter in this case.

**Comment by stefanor** [comment]
> it's much less error prone to treat then as string data

I was reading through the previous discussion of this in #9, and saw no mention of the 0o style, which is why I raise this here.

It seems this prefer for strings is because of the confusing 0 prefixes. But the other, 0o style is obviously not as confusing, and doesn't seem to have been considered.
