### ISSUE TITLE
FC 11.4.0 - FC086 False positive

### ISSUE THREAD

**Issue by stefanwb** [Foodcritic/foodcritic#685]
Foodcritic 11.4.0 throws an FC086 for these lines:
```
encrypted_item = Chef::EncryptedDataBagItem.encrypt_data_bag_item(original_item, Chef::EncryptedDataBagItem.load_secret)
```
and
```
bag = Chef::DataBagItem.new
```
These methods do not load items from a data bag but still trigger mentioned rule.

**Comment by tas50** [comment]
@stefanwb Thanks for the specific examples. I updated FC086 and used your examples in the specs to make sure we don't regress this in the future.

Fixed by https://github.com/Foodcritic/foodcritic/pull/696
