### ISSUE TITLE
FC104 fires on directory and cookbook_file

### ISSUE THREAD

**Issue by martinmosegaard** [Foodcritic/foodcritic#700]
I have a CI pipeline that just does a `gem install foodcritic` and I just got foodcritic 12.2.0 with the FC104 rule.

But it fires on a recipe with contents like this:

```
directory my_dir do
  recursive true
  action :create
end 

...

cookbook_file my_file_path do
  source node['some_attribute']
  action :create
end
```

But `action :run` does not make sense for these resources. Is this a bug in the rule?
Unfortunately, the pull request https://github.com/Foodcritic/foodcritic/pull/693 does not reference an issue, so it is hard to see the motivation for the new rule.

I may need to pin my foodcritic version.

**Comment by tas50** [comment]
@martinmosegaard I just noticed that this was broken on my own. I've added a spec that's failing right now and I'm going to get things green in foodcritic then do another release. Expect something in the next hour or two.

**Comment by tas50** [comment]
To clarify this should only be firing on ruby_blocks, but it's firing on all resources instead.

**Comment by tas50** [comment]
12.2.1 fixes this. I'll make sure we get this one into ChefDK current as well

**Comment by martinmosegaard** [comment]
Thanks for the fast turnaround! I have verified the fix. :+1:
