### ISSUE TITLE
FC019 false positive on `node.force_default`

### ISSUE THREAD

**Issue by haidangwa** [Foodcritic/foodcritic#715]
This looks like a re-occurrence of #181 
---------------------------------------

chefdk: 2.4.17

My cookbook wraps the ssh_known_hosts cookbook. Foodcritic throws this FC019 violation exactly as discussed in #181.

My Gemfile:
```
gem 'berkshelf', '~> 6.3.1'
gem 'chef', '~> 12'
gem 'chef-zero'
gem 'chefspec', '~> 7.1.0'
gem 'foodcritic', '~> 12.2.2'
gem 'inspec' # constrained by kitchen-inspec
gem 'kitchen-ec2', '~> 1.4.0'
gem 'kitchen-inspec', '~> 0.20'
gem 'kitchen-sync', '~> 2.1'
gem 'rubocop', '~> 0.51.0'
gem 'test-kitchen', '~> 1.19.2'
```

`FC019: Access node attributes in a consistent manner`: The line that it complains about simply does
```
node.force_default['sshd']['config']['AuthorizedKeysFile'] = '/etc/ssh/authorized_keys/%u'
```

Changing this to use `node.default` instead will get rid of the violation warning.

**Comment by TravisWhitehead** [comment]
I've researched this further. Even if I generate a `chef_dsl_metadata/chef_13.8.5.json` (beause I am using Chef 13.8.5) by following [these instructions](https://github.com/Foodcritic/foodcritic/blob/master/chef_dsl_metadata/README.md), this false-positive persists when I use `node.force_default`.

I noticed that in the generated file `force_default` is not present in the `dsl_methods` list, but if I add it to that list then no false-positive FC019 occurs.

In an old solution to #181, PR #364 [added `Chef::Node::Attribute.public_instance_methods` to `chef_node_methods` ](https://github.com/Foodcritic/foodcritic/pull/364/files#diff-d0a4237ec556e37293d4542e8fa30b58) as a solution to the FC019 false-positive discussed in #181.

I've tried adding `Chef::Node::Attribute.public_instance_methods` to `chef_dsl_methods` in [`chef_dsl_metadata/Rakefile`](https://github.com/Foodcritic/foodcritic/blob/master/chef_dsl_metadata/Rakefile#L21-L28) and have found that the files generated from this modified Rakefile no longer produce a false-positive FC019.

I'm unsure if this is a suitable solution, so I would like some input from the foodcritic community. I may make a PR soon requesting commentary on this fix.
