### ISSUE TITLE
FC011, FC031, & FC071 Fail when using root aliases 

### ISSUE THREAD

**Issue by drrk** [Foodcritic/foodcritic#739]
If you use root aliases (ie attributes.rb or recipe.rb in cookbook root) FC011, FC031, and FC071 fail when they don't fail if not using root aliases.

Tested with Chef Development Kit Version: 2.4.17 with foodcritic 12.2.1

**Comment by drrk** [comment]
Some more detail:

Kimballs-MacBook-Pro:test-root-alias kimball$ tree
.
├── Berksfile
├── Berksfile.lock
├── LICENSE
├── README.md
├── attributes
│   └── attributes.rb
├── chefignore
├── metadata.rb
├── recipe.rb
├── spec
│   ├── spec_helper.rb
│   └── unit
│       └── recipes
│           └── default_spec.rb
└── test
    └── smoke
        └── default
            └── default_test.rb

7 directories, 11 files
Kimballs-MacBook-Pro:test-root-alias kimball$ foodcritic .
Checking 4 files
.x..
FC011: Missing README in markdown format: ../README.md:1
FC031: Cookbook without metadata.rb file: ../metadata.rb:1
FC071: Missing LICENSE file: ../LICENSE:1
Kimballs-MacBook-Pro:test-root-alias kimball$

**Comment by drrk** [comment]
Replicating cookbook: http://bowerham.net/test-root-alias.zip 

Note I have patched my version of test-kitchen to work round the associated bug there: https://github.com/test-kitchen/test-kitchen/issues/1230

**Comment by tas50** [comment]
This is now fixed on master and I'll get a release out today
